name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          sudo apt-get purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell mysql* php* android*
          sudo apt-get autoremove && sudo apt-get autoclean

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev python3 python-is-python3 repo

      - name: Sync TWRP
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc)

      - name: Setup Device
        run: |
          mkdir -p ~/twrp/device/oukitel/WP27
          cp -r $GITHUB_WORKSPACE/* ~/twrp/device/oukitel/WP27/

      - name: Build
        run: |
          cd ~/twrp
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_WP27-eng
          make vendorbootimage -j$(nproc)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-WP27
          path: ~/twrp/out/target/product/WP27/vendor_boot.img
