name: Recovery Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Очистка диска (Максимальная)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h

      - name: Установка инструментов
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libssl-dev python3 python-is-python3 repo

      - name: Синхронизация TWRP (Минимум данных)
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --no-tags --no-clone-bundle --force-sync

      - name: Подготовка дерева устройства
        run: |
          mkdir -p ~/twrp/device/oukitel/WP27
          cp -r $GITHUB_WORKSPACE/* ~/twrp/device/oukitel/WP27/

      - name: Сборка
        run: |
          cd ~/twrp
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_WP27-eng
          make vendorbootimage -j$(nproc)

      - name: Загрузка результата
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-WP27-Ready
          path: ~/twrp/out/target/product/WP27/vendor_boot.img
